### PR TITLE
Remove usage of global variable

### PR DESCRIPTION
**Pull request by bekicot**
This pull request removes the usage of global variable
Another alternative is to use class variables.

### CODE REVIEW

**Comment by idleberg** [comment]
I understand that using a global variable isn't ideal, so my limited understanding of Ruby tells me to use a class (or instance?) variable instead. Unless you can make a convincing case of why your PR is better and is not just about personal taste. Take note, that `$os` is also used in the `install` method.

**Comment by bekicot** [comment]
It is nice to have feedback for this PR. The PR is still marked as work in progress, I forgot to add it on the first I made this pr.

I'm not sure if my pull request is better than the previous implementation. Please it does ignore it and close this issue.

However, I do search for usage of global variables in string interpolation in homebrew-core and linuxbrew-core, I only found it on  `Formula/freerdp.rb`. Hence I think it is uncommon. Or maybe my method of searching not appropriate. I use this
```
rg -e '\{\$'
```

**Comment by idleberg** [comment]
I guess instances variables are the way to go, I just remembered using them in an [official formula](https://github.com/Homebrew/homebrew-core/blob/93fbbd431df12c30e1551932b798b42bd31c513d/Formula/makensis.rb#L41) some time ago

**Comment by idleberg** [comment]
Superseded by 596531f7539a65916ae88fc29664b3a5c89e8a28

**Pull request closed without merging**
